version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    env_file:
      - .env
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3001:3001
    volumes:
      - ./src:/back/src
    depends_on:
      - db
#  front:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#     - 3000:3000
#    volumes:
#      - ./src:/front/src
#    depends_on:
#     - db


volumes:
  db:
    driver: local