version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    #volumes: 
    #  - db:/var/lib/postgresql/data
    #  - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: michalhosna/adminer
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DRIVER=pgsql
      - ADMINER_SERVER=postgres
      - ADMINER_USERNAME=${POSTGRES_USER}
      - ADMINER_DB=${POSTGRES_DB}
    ports:
      - "80:8080"
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - postgres
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/my-app/src
    depends_on:
     - postgres


volumes:
  db:
    driver: local