version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: 42_DB
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/back/src
    depends_on:
      - db
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    volumes:
      - ./src:/front/src
    depends_on:
     - db


volumes:
  db:
    driver: local